version: "3"
services:
  x-eureka-1:
    hostname: "x-eureka-1"
    image: "x-eureka-1:1.0"
    container_name: x-eureka-1
    ports:
      - "2101:2101"

  x-eureka-2:
    hostname: "x-eureka-2"
    image: "x-eureka-2:1.0"
    container_name: x-eureka-2
    ports:
      - "2102:2102"

